"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

interface ReportItem {
  id: string;
  weekStart: string;
  status: string;
  summary: string;
  url?: string | null;
}

export function ReportsCenter({
  initialReports,
}: {
  initialReports: ReportItem[];
}) {
  const [reports, setReports] = useState(initialReports);
  const [status, setStatus] = useState<string | null>(null);
  const [isQueueing, setIsQueueing] = useState(false);

  const queueReport = async () => {
    setIsQueueing(true);
    setStatus(null);
    try {
      const response = await fetch("/api/reports/weekly", {
        method: "POST",
      });
      const payload = (await response.json()) as {
        ok: boolean;
        report?: ReportItem;
        message?: string;
      };

      if (!payload.ok || !payload.report) {
        throw new Error(payload.message ?? "Unable to queue report.");
      }

      setReports((current) => [payload.report as ReportItem, ...current]);
      setStatus("Weekly report queued. Worker will generate PDF.");
    } catch (error) {
      setStatus(
        error instanceof Error
          ? error.message
          : "Could not queue report. Check DB schema first.",
      );
    } finally {
      setIsQueueing(false);
    }
  };

  return (
    <div className="space-y-5">
      <Card className="border-white/10 bg-slate-900/70">
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle>Your Week in Investing</CardTitle>
          <Button
            onClick={queueReport}
            disabled={isQueueing}
            className="bg-cyan-400 font-semibold text-slate-950 hover:bg-cyan-300"
          >
            {isQueueing ? "Queueing..." : "Queue Weekly PDF"}
          </Button>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-sm text-slate-300">
            Reports include performance, XP gained, streak status, charts, and behavior
            scores. PDFs are generated by background jobs.
          </p>
          {status ? <p className="text-xs text-slate-200">{status}</p> : null}
        </CardContent>
      </Card>

      <Card className="border-white/10 bg-slate-900/70">
        <CardHeader>
          <CardTitle>Report History</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          {reports.length === 0 ? (
            <p className="text-sm text-slate-300">No reports yet.</p>
          ) : (
            reports.map((report) => (
              <div
                key={report.id}
                className="rounded-lg border border-white/10 bg-white/5 p-3 text-sm"
              >
                <div className="flex items-center justify-between gap-2">
                  <p className="font-medium">
                    Week of {new Date(report.weekStart).toLocaleDateString()}
                  </p>
                  <span className="text-xs uppercase text-slate-300">{report.status}</span>
                </div>
                <p className="text-xs text-slate-300">{report.summary}</p>
                {report.url ? (
                  <a className="text-xs text-cyan-200 underline" href={report.url}>
                    Download PDF
                  </a>
                ) : null}
              </div>
            ))
          )}
        </CardContent>
      </Card>
    </div>
  );
}
